node {

    stage('SCM') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/roberthutto/react_jenkins.git'
        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.
    }
    stage('Build') {
        sh "./mvnw install"
    }
    stage('Results') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.jar'
    }
}